/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu;

import form.formMhs;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import java.awt.Component;

/**
 *
 * @author Robi Nurhidayat
 */
public class tampilanUtama extends javax.swing.JFrame {

    //buat kelas untuk UI baru
    public static class UIbaru extends Component {
    
        //buat constructor
        
        public UIbaru(){
            
        }
        
}
    /**
     * Creates new form tampilanUtama
     * 
     * 
     */
    
    //jika ingin mengcustome UI maka harus buat kelas nya terlebih dahulu
    //dengan extends ke component
    
 
    
    
    public tampilanUtama() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu5 = new javax.swing.JMenu();
        panelUtama = new javax.swing.JDesktopPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuLaporan = new javax.swing.JMenu();
        menuMhs = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuDosen = new javax.swing.JMenuItem();
        menuAbout = new javax.swing.JMenu();
        menuContact = new javax.swing.JMenu();

        jMenu5.setText("jMenu5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panelUtamaLayout = new javax.swing.GroupLayout(panelUtama);
        panelUtama.setLayout(panelUtamaLayout);
        panelUtamaLayout.setHorizontalGroup(
            panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        panelUtamaLayout.setVerticalGroup(
            panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        menuFile.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Keluar");
        menuFile.add(jMenuItem1);

        jMenuBar2.add(menuFile);

        menuLaporan.setText("Laporan");

        menuMhs.setText("Data Mahasiswa");
        menuMhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMhsActionPerformed(evt);
            }
        });
        menuLaporan.add(menuMhs);
        menuLaporan.add(jSeparator1);

        menuDosen.setText("Data Dosen");
        menuLaporan.add(menuDosen);

        jMenuBar2.add(menuLaporan);

        menuAbout.setText("About Us");
        jMenuBar2.add(menuAbout);

        menuContact.setText("Contact US");
        jMenuBar2.add(menuContact);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelUtama)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelUtama)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuMhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMhsActionPerformed
        // TODO add your handling code here:

        panelUtama.removeAll();
        panelUtama.repaint();
        formMhs mhs = new formMhs();
        
        //ambil sizeScreen 
        Dimension layarUtama = this.getSize();
        Dimension layarMhs = mhs.getSize();
        
        //simpan posisi frame Mhs ditengah 
        
        mhs.setLocation(layarUtama.width/2-layarMhs.width/2,layarUtama.height/2-layarMhs.height/2);
        
        panelUtama.add(mhs);
        mhs.setVisible(true);
    }//GEN-LAST:event_menuMhsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        try{
            
            UIManager.setLookAndFeel("com.jtattoo.plaf.aero.AeroLookAndFeel");
            SwingUtilities.updateComponentTreeUI(new UIbaru());
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"eror karena " + e);
        }
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tampilanUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu menuAbout;
    private javax.swing.JMenu menuContact;
    private javax.swing.JMenuItem menuDosen;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuLaporan;
    private javax.swing.JMenuItem menuMhs;
    private javax.swing.JDesktopPane panelUtama;
    // End of variables declaration//GEN-END:variables
}
